### PR TITLE
Project 7 implemented by Team 4

### PR DESCRIPTION
**Pull request by chinhuic**
Added the following:

1) TimeSeriesDistance.py
2) generateAndStoreTS.py
3) selectVPs.py
4) buildVPDBforest.py
5) mostSimilarTS.py

**Instructions below:**
Additional documentation can be found in the respective files.

Run the following on terminal window/command line window in the same directory where ArrayTimeSeries is stored.

1) Run 'Python generateAndStoreTS.py' to generate 1000 TS
2) Run 'buildVPDBforest.py' to create 20 database indexes
3) Run 'Python' in command line
4) Run 'import mostSimilarTS'
5) Search for the most similar TS by the following command:

	'mostSimilarTS.mostSimilarTS('./ts_100.npy', 10)'
	
	Output: 
	Nodes in search region =  1472
	['./ts_100.npy', './ts_586.npy', './ts_813.npy', './ts_106.npy', './ts_283.npy', './ts_283.npy', './ts_478.npy', './ts_478.npy', './ts_665.npy', './ts_248.npy']

### CODE REVIEW

**Comment by chinhuic** [comment]
looks great! thx!

@volauvent Can you please look into this?

**Comment by chinhuic** [comment]
@volauvent Could you look into this please?

**Comment by volauvent** [comment]
Hi Chin @chinhuic , could you add P7 in our "develop" branch and pull request again?

The code looks great! Thx!

**Comment by lyuqin** [comment]
Hi Chin @chinhuic ,
  We follow the standard development workflow: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow/ , where

> But, instead of branching off of master, feature branches use develop as their parent branch. When a feature is complete, it gets merged back into develop. Features should never interact directly with master.

Master branch is only used for releases (milestones), while develop branch is the place where we merge our features. So please fork our develop branch and make the pull request again. Thanks!

**Comment by chinhuic** [comment]
@lyuqin @volauvent Thanks both for pointing me to the branch. Wasn't aware of this dev branch when the fork was made. Will do!

**Pull request closed without merging**
